"""Pydantic models for API request/response and internal game state."""

from __future__ import annotations

from pydantic import BaseModel, Field


class GamePrompt(BaseModel):
    """User-supplied game idea."""

    prompt: str = Field(..., min_length=1, max_length=2000, description="User's game idea text")


class AssetRequirement(BaseModel):
    """A single asset to be generated by the Asset Agent."""

    name: str = Field(..., description="Snake-case identifier, e.g. player_sprite")
    type: str = Field(
        ..., pattern=r"^(image|audio_sfx|audio_music)$", description="Asset type"
    )
    description: str = Field(..., description="Prompt for generation")
    asset_url: str = Field(default="", description="Filled by Asset Agent at runtime")


class GameDesignDocument(BaseModel):
    """Structured game design document produced by the Director Agent."""

    title: str
    premise: str
    mechanics: list[str]
    controls: str
    win_condition: str
    loss_condition: str
    assets: list[AssetRequirement]
    canvas_width: int = 800
    canvas_height: int = 600
    background_color: str = "#2d2d2d"


class GameState(BaseModel):
    """Mutable pipeline state passed between agents."""

    game_id: str
    prompt: str
    gdd: GameDesignDocument | None = None
    assets: list[AssetRequirement] = []
    game_js: str = ""
    index_html: str = ""
    status: str = "pending"
    error: str | None = None


class GenerateResponse(BaseModel):
    """Response returned by the /api/generate-game endpoint."""

    game_id: str
    status: str
    message: str


class GameStatusResponse(BaseModel):
    """Response returned by the /api/game/{game_id} endpoint."""

    game_id: str
    status: str
    error: str | None = None


class APIStatus(BaseModel):
    """Status of a single API configuration."""
    configured: bool
    optional: bool
    label: str
    description: str


class ConfigResponse(BaseModel):
    """Current configuration status returned by GET /api/config."""
    llm_base_url: str
    llm_model: str
    llm_configured: bool
    image_api_url: str
    image_model: str
    image_configured: bool
    audio_api_url: str
    audio_model: str
    audio_configured: bool
    apis: dict[str, APIStatus]


class ConfigUpdate(BaseModel):
    """Fields the user can update via POST /api/config."""
    llm_base_url: str | None = None
    llm_api_key: str | None = None
    llm_model: str | None = None
    image_api_url: str | None = None
    image_api_key: str | None = None
    image_model: str | None = None
    audio_api_url: str | None = None
    audio_api_key: str | None = None
    audio_model: str | None = None
